<?xml version="1.0" encoding="utf-8"?><Database Name="NBA" Class="NBALeagueDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\NBA.mdf;Integrated Security=True" SettingsObjectName="LabCSharp.Properties.Settings" SettingsPropertyName="NBAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Teams" Member="Teams">
    <Type Name="Team">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Team_Student" Member="Students" ThisKey="Id" OtherKey="TeamId" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.Students" Member="Students">
    <Type Name="Student">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TeamId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Team_Student" Member="Team" ThisKey="TeamId" OtherKey="Id" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
</Database>