<?xml version="1.0" encoding="utf-8"?><Database Name="NBA" Class="NBALeagueDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\NBA.mdf;Integrated Security=True" SettingsObjectName="LabCSharp.Properties.Settings" SettingsPropertyName="NBAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Teams" Member="Teams">
    <Type Name="Team">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Team_Player" Member="Players" ThisKey="Id" OtherKey="TeamId" Type="Player" />
      <Association Name="Team_Game" Member="Games" ThisKey="Id" OtherKey="GuestTeamId" Type="Game" />
      <Association Name="Team_Game1" Member="Games1" ThisKey="Id" OtherKey="HostTeamId" Type="Game" />
      <Association Name="School_Team" Member="School" ThisKey="SchoolId" OtherKey="Id" Type="School" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schools" Member="Schools">
    <Type Name="School">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Association Name="School_Team" Member="Teams" ThisKey="Id" OtherKey="SchoolId" Type="Team" Cardinality="One" />
      <Association Name="School_Student" Member="Students" ThisKey="Id" OtherKey="SchoolId" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.Students" Member="Students">
    <Type Name="Student">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SchoolId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Student_Player" Member="Players" ThisKey="Id" OtherKey="StudentId" Type="Player" Cardinality="One" />
      <Association Name="School_Student" Member="School" ThisKey="SchoolId" OtherKey="Id" Type="School" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Players" Member="Players">
    <Type Name="Player">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeamId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Player_ActivePlayer" Member="ActivePlayers" ThisKey="Id" OtherKey="PlayerId" Type="ActivePlayer" />
      <Association Name="Student_Player" Member="Student" ThisKey="StudentId" OtherKey="Id" Type="Student" IsForeignKey="true" />
      <Association Name="Team_Player" Member="Team" ThisKey="TeamId" OtherKey="Id" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivePlayers" Member="ActivePlayers">
    <Type Name="ActivePlayer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GameId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PointsScored" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Played" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TeamId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Player_ActivePlayer" Member="Player" ThisKey="PlayerId" OtherKey="Id" Type="Player" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Game_ActivePlayer" Member="Game" ThisKey="GameId" OtherKey="Id" Type="Game" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Games" Member="Games">
    <Type Name="Game">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="HostTeamId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GuestTeamId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Game_ActivePlayer" Member="ActivePlayers" ThisKey="Id" OtherKey="GameId" Type="ActivePlayer" />
      <Association Name="Team_Game" Member="Team" ThisKey="GuestTeamId" OtherKey="Id" Type="Team" IsForeignKey="true" />
      <Association Name="Team_Game1" Member="Team1" ThisKey="HostTeamId" OtherKey="Id" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
</Database>